### PR TITLE
The current App::cloc fails to work on perl 5.22, this fixes that

### PR DESCRIPTION
**Pull request by pink-mist**
Perl 5.22 added a couple new errors such as using defined() on an array, and a couple of regular expression warnings involving unescaped {.

These commits changes the uses of defined() on arrays to simply check if the array is truthy, which is the correct way to check if an array exists.

It also adds \-escaping to { and } in regular expressions that are meant to be literal.

### CODE REVIEW

**Comment by pink-mist** [comment]
If you'd rather pull in upstream fixes you can close this PR with no hard feelings on my part.

**Comment by fibo** [comment]
Thanks, LGTM.
Actually, I contacted the cloc author to ask permissino for publish on CPAN, cuase I think it is the right place to put this beatiful script.
Now cloc is developed here: https://github.com/AlDanial/cloc
I will ask the author if he want to merge repos, otherwise I will fetch cloc later.

**Comment by AlDanial** [comment]
hi guys, thank you for your work to include and maintain cloc in CPAN.  The current git development branch of cloc (at the link @fibo points to in the post above), v1.67, runs cleanly in Perl 5.22.0 as far as I can tell, please correct me if I'm mistaken.  

The code you have here https://raw.githubusercontent.com/fibo/App-cloc-pm/master/bin/cloc, at v1.62, is pretty old.

Another change I made starting with the 1.66 release is including a stripped-down version of cloc that does not contain internal bundles of Regexp::Common and Algorithm::Diff.  This is the preferred version for package maintainers who can set up their installer instructions  to include these modules as external dependencies for cloc.  This cleaner version of cloc appears is in the Unix/ subdirectory of the 1.66 distribution.

**Comment by fibo** [comment]
I added it, and published on CPAN.

**About deps**: check the [Makefile.PL](https://github.com/fibo/App-cloc-pm/blob/master/Makefile.PL),  Regexp::Common and Algorithm::Diff are listed so they are installed when launching `cpan App::cloc`.

@pink-mist please let us know if cloc now fails on Perl `v.5.22`.
@AlDanial packaging was really easy, please tell me if you want a commit bit or you prefer I package it when you ping me.

**Comment by pink-mist** [comment]
Hi, no the current version of cloc on CPAN seems to have gotten 2 lines inserted at the top which make it fail to even be interpreted as a perl script when you simply run it. The lines are:
```

ciao
```
... Removing those two lines works fine though =)

**Comment by fibo** [comment]
Thanks for reporting it. Sorry I did a test to try instruction in *Creation* section.

Now it should be ok, I just release a `v1.67.1`.

Looking forward for a solution to merge the CPAN distribution into the main repo, or maybe @pink-mist you want to be able to release cloc.

Just let me know, I found useful to add cloc to CPAN, cause there are many benefits IMO.

**Pull request merged**
